-- Admin delete for shared gallery notes.
--
-- There is intentionally NO public DELETE policy for anon.
-- Do NOT enable:
--   -- create policy notes_delete_anon on public.notes
--   --   for delete to anon using (true);
--
-- Shared delete path: Edge Function `admin-delete-note`
--   (supabase/functions/admin-delete-note/index.ts)
-- which checks ADMIN_PIN / ADMIN_SECRET and deletes with the service role.
--
--   npx supabase secrets set ADMIN_PIN=... --project-ref ahisxvdbfjhhllysystl
--   npx supabase functions deploy admin-delete-note --project-ref ahisxvdbfjhhllysystl
--
-- Client: supabase.functions.invoke('admin-delete-note', { body: { id, pin } })
-- VITE_ADMIN_PIN is only a soft UI unlock (sessionStorage); the Edge Function
-- is the real check.
--
-- This migration is documentation-only (no-op). Safe to run.

select 1;
